# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sakura Kim
email: sakura.singer@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
                              Singer | MC | Event Planner
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sakurakim.info" # the base hostname & protocol for your site
paginate: 3
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
